#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#   Frederik Dudzik
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# ##########
# Functions
# ##########

function join { 
  local IFS="$1"; shift; echo "$*"; 
}

# #########
# VARIABLES
# #########

PATHS=(
  /usr/local/bin
  /usr/local/sbin
  /usr/bin
  /bin
  /usr/sbin
  /sbin
)

export PATH=$(join : ${PATHS[@]})

export EDITOR=vim
export MANPATH="/usr/local/man:$MANPATH"
export NVM_DIR=~/.nvm
export T_EXT=.txt
export T_FILE="todo${T_EXT}"
export T_DIR=~/iCloud/todos/

# #######
# aliases
# #######

alias v=vim

alias gaa="git add --all"
alias gd="git diff"
alias gdH="git diff HEAD"
alias gst="git status"

alias brews='brew list -1'
alias brewi='brew instal'
alias cask='brew cask'
alias bubo='brew update && brew outdated'
alias bubc='brew upgrade && brew cleanup'
alias bubu='bubo && bubc'

alias t=simple_task
alias tl=simple_task_list

# ############
# autocomplete
# ############

autoload bashcompinit
bashcompinit

complete -F rmapp_app_list rmapp
complete -F _simple_task_complete simple_task
complete -F _simple_task_list_complete simple_task_list
